baseURL = "https://becomethedragon.com"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Dragon Coach | Transformational Coaching"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.footer]]
URL = "about"
name = "About"
weight = 1
[[menu.footer]]
URL = "project"
name = "Project"
weight = 2
[[menu.footer]]
URL = "service"
name = "Service"
weight = 3
[[menu.footer]]
URL = "pricing"
name = "Pricing"
weight = 4
[[menu.footer]]
URL = "faq"
name = "FAQ"
weight = 5
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "project"
name = "Project"
weight = 2
[[menu.main]]
URL = "service"
name = "Service"
weight = 3
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 4
[[menu.main]]
hasChildren = true
name = "Pages"
weight = 5
[[menu.main]]
URL = "faq"
name = "FAQ"
parent = "Pages"
[[menu.main]]
URL = "pricing"
name = "Pricing"
parent = "Pages"
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 6
[params]
author = "Vlad-Emil Petrea"
contact_form_action = "#"
description = ""
email = "drachencoach@gmail.com"
google_analitycs_id = ""
location = "Aspettenstrasse 34, 2380, Perchtoldsdorf"
logo = "images/logo.png"
mobile = "+43 (0) 6506 733 755"
multi_author = false
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "48.126593"
map_longitude = "16.284252"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "https://www.linkedin.com/in/thedragonsoars"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "https://twitter.com/theDragonSoars"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "https://www.facebook.com/theDragonSoars"
